---
nginx:
  settings:
    user: "www-data"
    worker_processes: '{{ ansible_processor_cores }}'
    pid: "/run/nginx.pid"

  conf:

    events:
      worker_connections: 1024

    http:

      # Basic Settings
      sendfile: "on"
      tcp_nopush: "on"
      tcp_nodelay: "on"
      keepalive_timeout: 60
      types_hash_max_size: 2048
      default_type: "application/octet-stream"

      # Logging Settings
      access_log: "/var/log/nginx/access.log"
      error_log: "/var/log/nginx/error.log"

      # Gzip Settings
      gzip: "on"
      gzip_disable: \"msie6\"

    includes:
      - "/etc/nginx/conf.d/*.conf"
      - "/etc/nginx/sites-enabled/*"
      - "/etc/nginx/mime.types"


  # /etc/nginx/sites-available/rest.conf
  rest:
    server:
      listen: 443
      server_name: "{{ rest_url }}"
      ssl: "on"
      ssl_certificate: "/etc/ssl/certs/public.crt"
      ssl_certificate_key: "{{ ssl_key }}"
      ssl_protocols: "TLSv1 TLSv1.1 TLSv1.2"
      ssl_ciphers: "ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA"
      ssl_dhparam: "/etc/ssl/dhparam.pem"

    # location /
    proxy_params:
      proxy_set_header:
        "Host": "$host"
        "X-Real-IP": "$remote_addr"
        "X-Forwarded-For":  "$proxy_add_x_forwarded_for"
      proxy_pass:  "http://{{ rest_host }}:{{rest_port}}"
      proxy_redirect: "off"
      proxy_read_timeout:  60

